version: 2

sources:
  - name: gz_raw_data
    description: raw bigquery sources for sales,product, and shipping data
    tables:
      - name: raw_gz_sales
        description: Raw Sales data
      - name: raw_gz_product
        description: Raw product data
       
      - name: raw_gz_ship
        description: Raw shipping data
        
  

